### ISSUE TITLE
Error logs - invalid metric name 

### ISSUE THREAD

**Issue by RobiD** [bosh-prometheus/firehose_exporter#29] opened 2018-04-18 12:47 UTC
Dear @frodenas,

Our Firehose Exporter has been stable for a while, the upgrade to the latest version has fixed all the problems we had in the past. However, starting this morning, the exporter started to produce weird errors, see below:
```
[ERR] time="2018-04-18T12:40:36Z" level=error msg="[error gathering metrics: 2 error(s) occurred:\n* collected metric firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_queues_0_d_8748_f_6_8_c_33_4_c_51_99_ed_1_f_78_c_077761_e_deal_renewal_exchange_insurable_interest_service_depth label:<name:\"bosh_deployment\" value:\"cf-rabbitmq\" > label:<name:\"bosh_job_id\" value:\"0763273a-49d1-4615-8ce0-0e9cca4dbdcb\" > label:<name:\"bosh_job_ip\" value:\"10.16.190.138\" > label:<name:\"bosh_job_name\" value:\"rabbitmq-server\" > label:<name:\"environment\" value:\"adp\" > label:<name:\"origin\" value:\"p-rabbitmq\" > label:<name:\"unit\" value:\"count\" > gauge:<value:7 > has help \"Cloud Foundry Firehose '/p-rabbitmq/rabbitmq/queues/0d8748f6-8c33-4c51-99ed-1f78c077761e/DealRenewalExchange.insurableInterestService/depth' value metric from 'p-rabbitmq'.\" but should have \"Cloud Foundry Firehose '/p-rabbitmq/rabbitmq/queues/0d8748f6-8c33-4c51-99ed-1f78c077761e/DealRenewalExchange.insurable-interest-service/depth' value metric from 'p-rabbitmq'.\"\n* collected metric 

firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_queues_0_d_8748_f_6_8_c_33_4_c_51_99_ed_1_f_78_c_077761_e_deal_renewal_exchange_coverage_service_consumers label:<name:\"bosh_deployment\" value:\"cf-rabbitmq\" > label:<name:\"bosh_job_id\" value:\"0763273a-49d1-4615-8ce0-0e9cca4dbdcb\" > label:<name:\"bosh_job_ip\" value:\"10.16.190.138\" > label:<name:\"bosh_job_name\" value:\"rabbitmq-server\" > label:<name:\"environment\" value:\"adp\" > label:<name:\"origin\" value:\"p-rabbitmq\" > label:<name:\"unit\" value:\"count\" > gauge:<value:0 > has help \"Cloud Foundry Firehose '/p-rabbitmq/rabbitmq/queues/0d8748f6-8c33-4c51-99ed-1f78c077761e/DealRenewalExchange.coverageService/consumers' value metric from 'p-rabbitmq'.\" but should have \"Cloud Foundry Firehose '/p-rabbitmq/rabbitmq/queues/0d8748f6-8c33-4c51-99ed-1f78c077761e/DealRenewalExchange.coverage-service/consumers' value metric from 'p-rabbitmq'.\"]" source="firehose_exporter.go:118"
```

The `/metrics` endpoint itself works fine and shows all the metrics. But when we pull this endpoint from the Prometheus, we are getting the following error:
`invalid metric name "firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_queues_e_5_d_35_ba_5_1360_4514_8_a_04_6_b_850_fcd_1192_deal_renewal_exchange_anonymous_._p_qp_jrx_txe_gx_a_0_n_4_zyo_g_consumers"`

Could you please advise how to resolve this issue. Thanks!

Regards,
Robert

**Comment by RobiD** [comment] 2018-05-16 09:32
The above error started to occur again few days ago.  As already mentioned the `/metrics` endpoint itself works fine and shows all the metrics. But when we pull this endpoint from the Prometheus, we are getting the above error.

**Comment by aravind180** [comment] 2018-08-20 14:01
Dear Team,

We are facing ann error like below 
```

invalid metric name "firehose_value_metric_p_rabbitmq_p_rabbitmq_rabbitmq_queues_57851356_3_b_15_461_d_836_e_65_f_279371_ebb_deal_delete_exchange_anonymous_._q_cg_5_t_tb_w_7_e_mm_4_za_5_e_yg_consumers"
--

```

It was reported already by my colleague @RobiD . Could you please have a look into this.


Best Regards,
Aravind

**Comment by simonpasquier** [comment] 2019-01-07 16:57
Looks similar to #38

**Comment by robplahn** [comment] 2019-02-01 17:21
Agreed. This looks like the same issue we are facing on #38.  The problem is the '.' character.  We are using web stomp temporary queues which have randomly generated names.  When these names include a '.' or a '-' the regex truncates the metric name. This results in an invalid result for HELP, TYPE and metric entries since the truncation divides the name the second half of the name is passed as the rest of the TYPE, HELP or metric name and is invalid.  
As mentioned in #38 it appears that normalize_name.go util was developed to address these problems and perhaps can be expanded to handle these invalid characters as well.  
https://github.com/bosh-prometheus/firehose_exporter/blob/master/utils/normalize_name.go

**Comment by frodenas** [comment] 2019-02-02 05:33
This should be fixed at https://github.com/bosh-prometheus/firehose_exporter/commit/be93e2668f89ce2dd5d9c863748359966bd6f880. I'll cut a new release soon.

**Comment by frodenas** [comment] 2019-02-02 06:21
[v5.0.4](https://github.com/bosh-prometheus/firehose_exporter/releases/tag/v5.0.4) fixes this issue.

**Closed by frodenas** 2019-02-02 06:21 UTC
